---
- name: test de ping sur mes nodes
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks: 
    - name: faire un ping sur mes hôtes distants
      ping:
    - name: mise à jour des cache et des paquets
      apt:
        update_cache: yes
        upgrade: safe
